[project]
name = "article-share"
version = "1.0.0"
description = "Create beautiful Instagram stories to share articles/websites with!"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "lxml>=6.0.0",
    "pillow>=11.3.0",
    "requests>=2.32.4",
    "selenium>=4.34.0",
]
